services:
  db:
    image: postgres:18
    container_name: myapp_db
    env_file:
      - backend/.env
    environment:
      POSTGRES_DB: "FYP"
      POSTGRES_USER: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - appnet

  backend:
    build: ./backend
    container_name: myapp_backend
    env_file:
      - backend/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: myapp_frontend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8000"
    networks:
      - appnet

volumes:
  postgres_data: {}

networks:
  appnet:
    driver: bridge
