services:
  db:
    image: postgres:16
    container_name: myapp_db
    env_file:
      - backend/.env
    environment:
      POSTGRES_DB: "FYP"
      POSTGRES_USER: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d FYP"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - appnet
  
  redis:
    image: redis:7-alpine

  backend:
    build: ./backend
    container_name: myapp_backend
    env_file:
      - backend/.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: "postgresql://postgres:1234567890@db:5432/FYP"
      DB_USER: "postgres"
      DB_PASSWORD: "1234567890"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "FYP"
      CLERK_SECRET_KEY: "${CLERK_SECRET_KEY}"
      CLERK_JWKS_URL: "https://allowing-hamster-30.clerk.accounts.dev/.well-known/jwks.json"
      CORS_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      LANGSMITH_API_KEY: "${LANGSMITH_API_KEY}"
      LANGSMITH_TRACING_V2: "${LANGSMITH_TRACING_V2}"
      LANGSMITH_PROJECT: "${LANGSMITH_PROJECT}"
      MEMORY_MAX_FACTS: "${MEMORY_MAX_FACTS}"
      MEMORY_SNAPSHOT_PATH: "data/memory_snapshot.json"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: myapp_frontend
    env_file:
      - frontend/.env.local
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000/api"
    networks:
      - appnet

volumes:
  postgres_data: {}

networks:
  appnet:
    driver: bridge
